apiVersion: v1
entries:
  pan:
  - apiVersion: v1
    appVersion: V.0.1
    created: "2020-07-14T13:12:29.3907871Z"
    description: '&#039;Naast deze JSON rest API is er ook een [graphql](/graphql)
      interface beschikbaar.&#039;'
    digest: c540d105ed7cb8eac78ec33072a2cbe5b14f166e6da08aa1bb982553e2f7c733
    home: www.zuid-drecht.nl
    icon: www.zuid-drecht.nl
    name: pan
    urls:
    - pan-0.1.0.tgz
    version: 0.1.0
  pc:
  - apiVersion: v1
    appVersion: V.0.1
    created: "2020-07-14T13:12:29.3999712Z"
    description: '&#039;Naast deze JSON rest API is er ook een [graphql](/graphql)
      interface beschikbaar.&#039;'
    digest: 0b241991c441ce65541b5bc63bebefe1242253a97b5fa8fbdc1894437ed12591
    home: pc.zaakonline.nl
    icon: pc.zaakonline.nl
    name: pc
    urls:
    - pc-0.1.0.tgz
    version: 0.1.0
generated: "2020-07-14T13:12:29.3823684Z"
